version: '3'

services:

  database:
    image: mysql:latest
    container_name: database-mysql
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - '3307:3306'
    expose:
      - 3307
    environment:
      MYSQL_DATABASE: 'beegbrain'
      MYSQL_PORT: '3306'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'

  django:
    build: ./projBackend/beegbrain
    volumes:
      - /backend:/backend
    ports:
      - "8080:8080"
    image: django
    container_name: backend-django
    restart: unless-stopped
    depends_on:
      - database

  angular:
    build: ./projFrontend/beegbrain
    image: angular
    container_name: frontend-angular
    restart: unless-stopped
    depends_on:
      - django
      - database

# adicionar volumes