version: '3'

services:

  db:
    image: mysql:latest
    container_name: database-mysql
    restart: unless-stopped
    ports:
      - '3307:3306'
    environment:
      MYSQL_DATABASE: 'beegbrain'
      MYSQL_PORT: '3307'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      timeout: 5s
      retries: 30
    volumes:
      - ~/mysql:/var/lib/mysql

  django:
    build: ./projBackend/beegbrain
    ports:
      - "8000:8000"
    image: django
    container_name: backend-django
    command: python manage.py runserver 0.0.0.0:8000
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - /tmp/mysqld:/run/mysqld
    links:
      - db

  angular:
    build: ./projFrontend/beegbrain
    image: angular
    ports:
      - "4200:80"
    container_name: frontend-angular
    restart: unless-stopped
    depends_on:
      - django


volumes:
  mysql: