# Generated by Django 2.2.4 on 2022-05-03 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EEG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=50)),
                ('filetype', models.CharField(max_length=10)),
                ('file', models.FileField(upload_to='')),
                ('status', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=300)),
                ('telephone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('health_number', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=300)),
                ('telephone', models.CharField(max_length=20)),
                ('birthday', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('health_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.Person', verbose_name='health_number')),
                ('medical_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('health_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.Person', verbose_name='health_number')),
                ('medical_info', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Providence',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.Institution', verbose_name='id')),
            ],
        ),
        migrations.CreateModel(
            name='RevisionCenter',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.Institution', verbose_name='id')),
            ],
        ),
        migrations.CreateModel(
            name='SharedFolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eeg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.EEG', verbose_name='eeg')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Institution', verbose_name='institution')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('eeg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.EEG', verbose_name='eeg')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Person', verbose_name='person')),
            ],
        ),
        migrations.AddField(
            model_name='eeg',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Report', verbose_name='report'),
        ),
        migrations.CreateModel(
            name='AccessEEG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eeg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.EEG', verbose_name='eeg')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Person', verbose_name='person')),
            ],
        ),
        migrations.AddField(
            model_name='report',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Doctor', verbose_name='doctor'),
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('health_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.Person', verbose_name='health_number')),
                ('operator_number', models.CharField(max_length=20)),
                ('providence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Providence', verbose_name='providence')),
            ],
        ),
        migrations.AddField(
            model_name='eeg',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Operator', verbose_name='operator'),
        ),
        migrations.AddField(
            model_name='eeg',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Patient', verbose_name='patient'),
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('providence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Providence', verbose_name='providence')),
                ('revision_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.RevisionCenter', verbose_name='revision_center')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorRevisionCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Doctor', verbose_name='doctor')),
                ('revision_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.RevisionCenter', verbose_name='revision_center')),
            ],
            options={
                'unique_together': {('doctor', 'revision_center')},
            },
        ),
    ]
