# Generated by Django 2.2.4 on 2022-05-05 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedfolder',
            name='path',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='doctorrevisioncenter',
            name='revision_center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.RevisionCenter', verbose_name='revision center'),
        ),
    ]
